### ISSUE TITLE
No curriculum or solution branch

### ISSUE THREAD

**Issue by jessepisel** [learn-co-curriculum/dsc-xgboost-deloitte-pyspark#1]
## Issue Subtype

- [ ] Master branch code
- [x] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

### Concern

Needs a solution and curriculum branch to match curriculum standards. 

## What OS Are You Using?

- [x] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [x] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
We have a solution (if not quite pretty) and a curriculum branch now.
